import { tenantRepository } from '../../database/tenant-repository';
import { TipoDocumentoIdentidad } from './tipo-documento-identidad.entity';
import { TipoComprobante } from './tipo-comprobante.entity';
import { UnidadMedida } from './unidad-medida.entity';
import { TipoAfectacionIgv } from './tipo-afectacion-igv.entity';
import { TipoOperacion } from './tipo-operacion.entity';
import { MedioPago } from './medio-pago.entity';
import { Banco } from './banco.entity';
import { Pais } from './pais.entity';
import { DivisionAdministrativa } from './division-administrativa.entity';
import { MotivoTraslado } from './motivo-traslado.entity';
import { ModalidadTraslado } from './modalidad-traslado.entity';
import { MotivoNota } from './motivo-nota.entity';

export const tipoDocumentoIdentidadRepository = tenantRepository(TipoDocumentoIdentidad);
export const tipoComprobanteRepository = tenantRepository(TipoComprobante);
export const unidadMedidaRepository = tenantRepository(UnidadMedida);
export const tipoAfectacionIgvRepository = tenantRepository(TipoAfectacionIgv);
export const tipoOperacionRepository = tenantRepository(TipoOperacion);
export const medioPagoRepository = tenantRepository(MedioPago);
export const bancoRepository = tenantRepository(Banco);
export const paisRepository = tenantRepository(Pais);
export const divisionAdministrativaRepository = tenantRepository(DivisionAdministrativa);
export const motivoTrasladoRepository = tenantRepository(MotivoTraslado);
export const modalidadTrasladoRepository = tenantRepository(ModalidadTraslado);
export const motivoNotaRepository = tenantRepository(MotivoNota);
