import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes';
import { demoRouter } from '../modules/demo/demo.routes';
import { cartaPublicaRouter } from '../modules/carta-publica/carta-publica.routes';
import { suscripcionRouter } from '../modules/suscripcion/suscripcion.routes';
import { configuracionRouter } from '../modules/configuracion/configuracion.routes';
import { plataformaRouter } from '../modules/plataforma/plataforma.routes';
import { empresaRouter } from '../modules/empresa/empresa.routes';
import { personalRouter } from '../modules/personal/personal.routes';
import { usuarioRouter } from '../modules/usuarios/usuario.routes';
import { rolRouter } from '../modules/roles/rol.routes';
import { permisoRouter } from '../modules/permisos/permiso.routes';
import { catalogosRouter } from '../modules/catalogos/catalogos.routes';
import { categoriaRouter } from '../modules/categorias/categoria.routes';
import { marcaRouter } from '../modules/marcas/marca.routes';
import { productoRouter } from '../modules/productos/producto.routes';
import { salonRouter } from '../modules/salones/salon.routes';
import { mesaRouter } from '../modules/mesas/mesa.routes';
import { clienteRouter } from '../modules/clientes/cliente.routes';
import { reservaRouter } from '../modules/reservas/reserva.routes';
import { pedidoRouter } from '../modules/pedidos/pedido.routes';
import { comandaRouter } from '../modules/cocina/comanda.routes';
import { ventaRouter } from '../modules/ventas/venta.routes';
import { talonarioRouter } from '../modules/talonario/talonario.routes';
import { cobranzaRouter } from '../modules/cobranzas/cobranza.routes';
import { pagoRouter } from '../modules/cobranzas/pago.routes';
import { cajaRouter } from '../modules/caja/caja.routes';
import { almacenRouter } from '../modules/almacenes/almacen.routes';
import { insumoRouter } from '../modules/insumos/insumo.routes';
import { recetaRouter } from '../modules/recetas/receta.routes';
import { costeoRouter } from '../modules/recetas/costeo.routes';
import { reporteRouter } from '../modules/reportes/reporte.routes';
import { auditoriaRouter } from '../modules/auditoria/auditoria.routes';
import { existenciaRouter } from '../modules/inventario/existencia.routes';
import { proveedorRouter } from '../modules/proveedores/proveedor.routes';
import { compraRouter } from '../modules/compras/compra.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/demo', demoRouter);
apiRouter.use('/publico', cartaPublicaRouter);
apiRouter.use('/suscripcion', suscripcionRouter);
apiRouter.use('/configuracion', configuracionRouter);
// Panel del proveedor del sistema. Se llama `plataforma` y no `proveedor` para no
// confundirlo con `/proveedores`, que son los proveedores de insumos del restaurante.
apiRouter.use('/plataforma', plataformaRouter);
apiRouter.use('/empresas', empresaRouter);
apiRouter.use('/personal', personalRouter);
apiRouter.use('/usuarios', usuarioRouter);
apiRouter.use('/roles', rolRouter);
apiRouter.use('/permisos', permisoRouter);
apiRouter.use('/catalogos', catalogosRouter);
apiRouter.use('/categorias', categoriaRouter);
apiRouter.use('/marcas', marcaRouter);
apiRouter.use('/productos', productoRouter);
apiRouter.use('/salones', salonRouter);
apiRouter.use('/mesas', mesaRouter);
apiRouter.use('/clientes', clienteRouter);
apiRouter.use('/reservas', reservaRouter);
apiRouter.use('/pedidos', pedidoRouter);
apiRouter.use('/comandas', comandaRouter);
apiRouter.use('/ventas', ventaRouter);
apiRouter.use('/talonarios', talonarioRouter);
apiRouter.use('/cuentas-por-cobrar', cobranzaRouter);
apiRouter.use('/pagos-venta', pagoRouter);
apiRouter.use('/cajas', cajaRouter);
apiRouter.use('/almacenes', almacenRouter);
apiRouter.use('/insumos', insumoRouter);
apiRouter.use('/recetas', recetaRouter);
apiRouter.use('/costeo', costeoRouter);
apiRouter.use('/reportes', reporteRouter);
apiRouter.use('/auditoria', auditoriaRouter);
apiRouter.use('/existencias', existenciaRouter);
apiRouter.use('/proveedores', proveedorRouter);
apiRouter.use('/compras', compraRouter);
